# Generated by Django 5.1.3 on 2025-09-22 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-rating', 'name']},
        ),
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_registration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dashboard_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_dashboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_areas',
            field=models.TextField(blank=True, help_text='Areas where supplier delivers'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri: 8AM-6PM, Sat: 8AM-4PM', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_shops/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='years_in_business',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_products/'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_products/'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='category',
            field=models.CharField(choices=[('tiles', 'Tiles'), ('cement', 'Cement'), ('sand', 'Sand'), ('grout', 'Grout'), ('adhesive', 'Adhesive'), ('tools', 'Tools'), ('hardware', 'Hardware'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('bag', 'Bag'), ('ton', 'Ton'), ('cubic_meter', 'Cubic Meter'), ('square_meter', 'Square Meter'), ('liter', 'Liter'), ('kilogram', 'Kilogram')], max_length=50),
        ),
    ]
