# Generated by Django 4.2.20 on 2025-04-28 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity needed for this project BEFORE wastage. Set by views/external logic.', max_digits=12, verbose_name='Quantity Needed (Raw)'),
        ),
    ]
