# Generated by Django 4.2.20 on 2025-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='project Location'),
        ),
    ]
