# Generated by Django 4.2.20 on 2025-05-02 15:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsetting',
            name='role_coverage_defaults',
            field=models.JSONField(default={'default': {'floor': 10.0, 'wall': 10.0}, 'labourer': {'floor': 0.0, 'wall': 0.0}, 'master': {'floor': 44.0, 'wall': 83.0}, 'painter': {'floor': 0.0, 'wall': 12.0}, 'tiler': {'floor': 14.0, 'wall': 12.0}}, help_text='JSON structure defining default coverage rates per worker role and work type (floor/wall).', verbose_name='Role Coverage Defaults'),
        ),
        migrations.AddField(
            model_name='project',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='profit'),
        ),
    ]
