# Generated by Django 4.2.20 on 2025-05-02 15:55

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_dynamicsetting_role_coverage_defaults_project_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsetting',
            name='role_coverage_defaults',
            field=models.JSONField(default=projects.models.get_default_role_coverage_data, help_text='JSON structure defining default coverage rates per worker role and work type (floor/wall).', verbose_name='Role Coverage Defaults'),
        ),
    ]
