# Generated by Django 4.2.20 on 2025-05-02 17:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_dynamicsetting_role_coverage_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_floor_area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Total Floor Area'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_wall_area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Total Wall Area'),
        ),
    ]
