# Generated by Django 4.2.20 on 2025-05-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subtotal_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_material_cost',
        ),
        migrations.RemoveField(
            model_name='projectmaterial',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='projectmaterial',
            name='unit_price',
        ),
    ]
