# Generated by Django 4.2.20 on 2025-05-22 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectmaterial_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mortar_thickness',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='The thcikness of the cement to be added.', max_digits=5, verbose_name='Mortar thickness)'),
        ),
    ]
