# Generated by Django 5.1.3 on 2025-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_mortar_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='feet', max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
