# Generated by Django 5.1.3 on 2025-06-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_material_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Unit'),
        ),
    ]
