# Generated by Django 5.1.3 on 2025-06-17 04:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_area_with_waste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Floor Area Calculated with waste'),
        ),
        migrations.AddField(
            model_name='room',
            name='total_area_with_waste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total Area Calculated with waste'),
        ),
        migrations.AddField(
            model_name='room',
            name='wall_area_with_waste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Wall Area Calculated with waste'),
        ),
    ]
