# Generated by Django 5.1.3 on 2025-06-18 00:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_room_floor_area_with_waste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_area_with_waste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total Area Calculated'),
        ),
    ]
