# Generated by Django 5.1.3 on 2025-07-06 17:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_total_area_with_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_floor_area_with_waste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Total Floor Area with waste'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_wall_area_with_waste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Total Wall Area with waste'),
        ),
    ]
