# Generated by Django 4.2.20 on 2025-05-06 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name or company name.", max_length=255)),
                ('phone', models.CharField(blank=True, help_text="Customer's phone number.", max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text="Customer's address or general location.", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user/company associated with this customer.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Estimate', help_text='A title for the estimate.', max_length=255)),
                ('estimate_date', models.DateField(auto_now_add=True, help_text='The date the estimate was created.')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost for transport.', max_digits=10)),
                ('remarks', models.TextField(blank=True, help_text='Any additional remarks or notes for the estimate.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer for this estimate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='manual_estimate.customer')),
                ('user', models.ForeignKey(help_text='The user/company who created this estimate.', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the room or area.', max_length=255)),
                ('type', models.CharField(blank=True, help_text="Type of room or area (e.g., 'Bedroom', 'Kitchen').", max_length=100, null=True)),
                ('floor_area', models.DecimalField(decimal_places=2, default=0.0, help_text='Floor area in square meters.', max_digits=10)),
                ('wall_area', models.DecimalField(decimal_places=2, default=0.0, help_text='Wall area in square meters.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(help_text='The estimate this room/area belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='manual_estimate.estimate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the material.', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit of the material.', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the material used.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(help_text='The estimate this material item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='manual_estimate.estimate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabourItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role or description of the labour.', max_length=255)),
                ('count', models.PositiveIntegerField(default=1, help_text='Number of individuals or units.')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit (e.g., per hour, per day, per project).', max_digits=10)),
                ('rate_type', models.CharField(blank=True, help_text="Type of rate (e.g., 'hourly', 'daily', 'fixed').", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(help_text='The estimate this labour item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='manual_estimate.estimate')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
