# Generated by Django 4.2.20 on 2025-05-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_estimate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimated_days',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated number of days ', max_digits=10),
        ),
        migrations.AddField(
            model_name='estimate',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total profit ', max_digits=10),
        ),
    ]
