# Generated by Django 4.2.20 on 2025-05-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual_estimate', '0002_estimate_estimated_days_estimate_profit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
