# Generated by Django 4.2.20 on 2025-05-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manual_estimate', '0003_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='manual_estimate.customer'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimated_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='title',
            field=models.CharField(default='New Estimate', max_length=255),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labouritem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='labouritem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='manual_estimate.estimate'),
        ),
        migrations.AlterField(
            model_name='labouritem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labouritem',
            name='rate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labouritem',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='manual_estimate.estimate'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomarea',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='manual_estimate.estimate'),
        ),
        migrations.AlterField(
            model_name='roomarea',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomarea',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomarea',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomarea',
            name='wall_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
