# Generated by Django 4.2.20 on 2025-05-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_estimate', '0004_alter_customer_location_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='wastage_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
