# Generated by Django 4.2.20 on 2025-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_estimate', '0005_estimate_wastage_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='profit',
        ),
        migrations.AddField(
            model_name='estimate',
            name='labour_cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of labour for one day.', max_digits=10, verbose_name='Labour Cost Per Day'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='labour_per_sq_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total profit per square meter'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='profit_type',
            field=models.CharField(default=45, max_length=20, verbose_name='Original Profit Type Input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='profit_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Original Profit Value Input'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='total_area_sq_m',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total area in square meters'),
        ),
        migrations.DeleteModel(
            name='LabourItem',
        ),
    ]
