# Generated by Django 4.2.20 on 2025-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_estimate', '0006_remove_estimate_profit_estimate_labour_cost_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='total_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total labour cost '),
        ),
    ]
