# Generated by Django 5.1.3 on 2025-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_estimate', '0007_estimate_total_labour_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='project_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
