# Generated by Django 4.2.20 on 2025-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='manual_estimate_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='manual_estimate_limit',
            field=models.PositiveBigIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='manual_estimates_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='three_d_views_limit',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
