# Generated by Django 5.1.3 on 2025-05-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_manual_estimate_limit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
