# Generated by Django 5.1.3 on 2025-05-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=20)),
                ('force_update', models.BooleanField(default=True)),
                ('update_message', models.TextField()),
                ('download_link', models.URLField()),
                ('platform', models.CharField(default='android', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
