# Generated by Django 5.1.3 on 2025-06-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='manual_estimate_limit',
            field=models.PositiveBigIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='project_limit',
            field=models.PositiveBigIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='three_d_views_limit',
            field=models.PositiveBigIntegerField(default=30),
        ),
    ]
