# Generated by Django 5.1.3 on 2025-06-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usersubscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='manual_estimate_limit',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='project_limit',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='three_d_views_limit',
            field=models.PositiveBigIntegerField(default=15),
        ),
    ]
