# Generated by Django 4.2.20 on 2025-04-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_type', models.CharField(choices=[('tiles', 'Tiles'), ('pavement', 'Pavement'), ('masonry', 'Masonry'), ('carpentry', 'Carpentry')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('tiles', 'Tiles'), ('pavement', 'Pavement'), ('masonry', 'Masonry'), ('carpentry', 'Carpentry')], max_length=20)),
                ('room_type', models.CharField(choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('dining', 'Dining'), ('corridor', 'Corridor'), ('fence_wall', 'Fence Wall'), ('porch', 'Porch'), ('room', 'Room')], max_length=20)),
                ('measurement_unit', models.CharField(choices=[('meters', 'Meters'), ('feet', 'Feet'), ('inches', 'Inches'), ('centimeters', 'Centimeters')], max_length=20)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_thickness', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('auto_wastage', models.BooleanField(default=True)),
                ('manual_wastage_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_estimates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='estimates.quickestimate')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.material')),
            ],
        ),
    ]
