# admin_api/urls.py

from django.urls import path, include # Import include to include router URLs
from rest_framework_simplejwt.views import TokenRefreshView # Import TokenRefreshView if needed
from rest_framework_simplejwt.views import TokenObtainPairView # Import the base Simple JWT view

# --- Import your custom superuser serializer from your accounts app ---
# Make sure the path is correct based on where your accounts app is located
from .serializers import SuperuserTokenObtainPairSerializer

# --- Import your admin views from the current app (admin_api) ---
from .views import (
    AdminStatsView,
    UserViewSet, # Assuming you are using the UserViewSet
    PermissionListView,
    GroupListView,
    request_password_reset_sms,
    verify_password_reset_code,
    # Import any other admin views you have defined in admin_api/views.py
)

# Import DefaultRouter for ViewSets
from rest_framework.routers import DefaultRouter

# Create a router instance for your ViewSets
# Routers automatically generate URL patterns for ViewSets (list, detail, etc.)
router = DefaultRouter()

# Register your UserViewSet with the router.
# The first argument 'users' is the URL prefix for this ViewSet (e.g., /admin/users/)
# The second argument is the ViewSet class itself.
# The third argument 'basename' is used to generate URL names (e.g., 'user-list', 'user-detail').
# It's required if your ViewSet does not have a .queryset attribute.
router.register(r'users', UserViewSet, basename='user')

# Define the URL patterns for the admin API app
urlpatterns = [
    # --- Simple JWT Superuser Login Endpoint ---
    # This path maps the URL 'login/' to Simple JWT's TokenObtainPairView.
    # We pass our custom SuperuserTokenObtainPairSerializer to ensure
    # only superusers can obtain tokens from this endpoint.
    # The name='admin_login' provides a convenient way to reference this URL.
    # Example usage in frontend: POST to /api/admin/login/ (assuming main urls.py setup)
    path('login/', TokenObtainPairView.as_view(serializer_class=SuperuserTokenObtainPairSerializer), name='admin_login'),

    # --- Simple JWT Token Refresh Endpoint ---
    # This path maps the URL 'token/refresh/' to Simple JWT's TokenRefreshView.
    # This endpoint is used by the frontend to get a new access token using a refresh token.
    # Example usage in frontend: POST to /api/admin/token/refresh/
    # Uncomment the line below if you need token refreshing for your admin frontend.
    # path('token/refresh/', TokenRefreshView.as_view(), name='admin_token_refresh'),


    # --- URLs for your other Admin API Views ---

    # Endpoint for aggregate statistics
    # Example URL: /api/admin/stats/
    path('stats/', AdminStatsView.as_view(), name='admin_stats'),

    # Endpoint to list all available Django Permissions
    # Example URL: /api/admin/permissions/
    path('permissions/', PermissionListView.as_view(), name='permission_list'),

    # Endpoint to list all available Django Groups
    # Example URL: /api/admin/groups/
    path('groups/', GroupListView.as_view(), name='group_list'),

    # --- Include ViewSet URLs generated by the router ---
    # This line includes all the URL patterns automatically generated by the router
    # for the registered ViewSets (like UserViewSet).
    # It places these URLs at the root of this admin_api app's URL space.
    # Example URLs generated by router.register(r'users', UserViewSet, ...):
    # GET /api/admin/users/ -> list action (UserViewSet.list)
    # POST /api/admin/users/ -> create action (UserViewSet.create)
    # GET /api/admin/users/{pk}/ -> retrieve action (UserViewSet.retrieve)
    # PUT /api/admin/users/{pk}/ -> update action (UserViewSet.update)
    # PATCH /api/admin/users/{pk}/ -> partial_update action (UserViewSet.partial_update)
    # DELETE /api/admin/users/{pk}/ -> destroy action (UserViewSet.destroy)
    path('', include(router.urls)),

    # Password Reset SMS Endpoints
    path('password-reset/request/', request_password_reset_sms, name='request_password_reset_sms'),
    path('password-reset/verify/', verify_password_reset_code, name='verify_password_reset_code'),
    
    # Add other specific admin API URLs here as needed
    # Example: path('some-other-admin-endpoint/', SomeOtherAdminView.as_view(), name='some_other_admin_endpoint'),
]
