# Generated by Django 5.1.3 on 2025-05-27 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='email',
            field=models.EmailField(default='fallback@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_response',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='mobile_operator',
            field=models.CharField(default='mtn', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_amount_pesewas',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_response_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='phone_number',
            field=models.CharField(default='02040593948', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
