# Generated by Django 5.1.3 on 2025-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
