# Generated by Django 5.1.3 on 2025-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_paymenttransaction_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
