# Generated by Django 5.1.3 on 2025-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paystack_response_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
